# Generated by Django 2.2 on 2019-05-03 04:25

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

# upload_to=movie.models.generate_filename

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField()),
                ('country', models.CharField(db_index=True, max_length=30)),
                ('genre', models.CharField(db_index=True, max_length=30)),
                ('actors', models.CharField(db_index=True, max_length=150)),
                ('duration', models.CharField(db_index=True, max_length=20)),
                ('director', models.CharField(db_index=True, max_length=40)),
                ('age', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(db_index=True)),
            ],
        ),
    ]
