# Generated by Django 2.2 on 2019-05-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
    ]
