# Generated by Django 2.2 on 2019-05-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190504_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информация'},
        ),
    ]
