# Generated by Django 2.2 on 2019-05-04 05:51

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190504_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Актерский состав'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Страна производства'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(db_index=True, max_length=40, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to=movie.models.generate_filename, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название фильма'),
        ),
    ]
