# Generated by Django 2.2 on 2019-05-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20190504_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='address',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(db_index=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='about',
            name='email_field',
            field=models.CharField(db_index=True, max_length=50, verbose_name='E-mail'),
        ),
    ]
