# Generated by Django 2.2 on 2019-05-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20190504_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(db_index=True, max_length=30, verbose_name='Имя автора')),
                ('comment_text', models.TextField(db_index=True, verbose_name='Текст комментария')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('comment_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
