# Generated by Django 2.2 on 2019-05-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(default='example@mail.com', max_length=75),
            preserve_default=False,
        ),
    ]
