# Generated by Django 2.2 on 2019-05-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20190506_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_email',
            field=models.EmailField(max_length=75, verbose_name='Адрес электронной почты'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_date', models.DateTimeField(verbose_name='Дата фильма')),
                ('movie_price', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Стоимость билета')),
                ('movie_format', models.CharField(choices=[('4D', '4D'), ('IMAX', 'IMAX 3D'), ('3D', '3D'), ('2D', '2D')], db_index=True, max_length=2, verbose_name='Формат фильма')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie', verbose_name='Название фильма')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
