# Generated by Django 2.2 on 2019-05-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_auto_20190509_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='hall_places_count',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=2, verbose_name='Число мест в ряду'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='hall_rows_count',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=2, verbose_name='Число рядов'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_row', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Ряд')),
                ('hall_place', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Место')),
                ('place_num', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='МестоБД')),
                ('is_bought', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.Schedule', verbose_name='Фильм')),
            ],
        ),
    ]
