# Generated by Django 2.2 on 2019-05-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_auto_20190509_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='hall_place',
            field=models.CharField(db_index=True, max_length=2, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='place',
            name='hall_row',
            field=models.CharField(db_index=True, max_length=2, verbose_name='Ряд'),
        ),
    ]
