# Generated by Django 2.2 on 2019-05-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_auto_20190515_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_bought',
            field=models.BooleanField(default=True, verbose_name='Куплено?'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='movie_format',
            field=models.CharField(choices=[('4D', '4D'), ('IMAX', 'IMAX 3D'), ('3D', '3D'), ('2D', '2D')], db_index=True, max_length=4, verbose_name='Формат фильма'),
        ),
    ]
